
services:

  db:
    image: mysql:8.0.45
    container_name: smspenzi-db
    restart: unless-stopped

    env_file:
      - .env

    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}  


    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql


  backend:
    build: ./smspenzi
    container_name: smspenzi-backend
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - .env

    environment:
      - MYSQL_HOST=${MYSQL_HOST:-db}
      - MYSQL_PORT=${MYSQL_PORT:-3306}


    ports:
      - "5000:5000"

      
  frontend:
    build: ./penzi-frontend
    container_name: penzi-frontend
    restart: unless-stopped
    depends_on:
      - backend
    env_file:
      - .env

    environment:
      - VITE_API_PROXY_TARGET=${VITE_API_PROXY_TARGET}
      
    ports:
      - "5173:5173"

volumes:
  mysql_data: